# Generated by Django 5.1.6 on 2025-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_image_mini',
        ),
    ]
