# Generated by Django 5.1.6 on 2025-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_project_thumbnail_image_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_image_mini',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails_mini/'),
        ),
    ]
