# Generated by Django 5.1.6 on 2025-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_project_thumbnail_image_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='Made with Love', max_length=200),
        ),
    ]
