# Generated by Django 5.1.6 on 2025-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails_banner/'),
        ),
    ]
