# Generated by Django 5.1.6 on 2025-02-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_project_similar_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail_image_mini',
            new_name='carousel_images',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='similar_description',
            new_name='small_description',
        ),
    ]
