# Generated by Django 5.1.6 on 2025-02-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_thumbnail_image_mini_project_carousel_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='carousel_images',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/carousel/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='frontend.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
